#!C:\Users\Admin\RhythmGameProject\Assets\StreamingAssets\Embedded Python\python-3.7.0-embed-amd64\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
